#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Aug 26 16:44:21 EDT 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_top_level_behav -key {Behavioral:sim_1:Functional:test_top_level} -tclbatch test_top_level.tcl -view /home/intern/FPGA_Projects/testbench_behav2.wcfg -log simulate.log"
xsim test_top_level_behav -key {Behavioral:sim_1:Functional:test_top_level} -tclbatch test_top_level.tcl -view /home/intern/FPGA_Projects/testbench_behav2.wcfg -log simulate.log

